name = "QUBO_encoding"
uuid = "1de9590e-19ab-4356-9c3b-958b221cba3d"
authors = ["Cmurilochem <carlosmurilorocha@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
